### ISSUE TITLE
Stop using bit-rotted library generator CMake routines in Legate core

### ISSUE THREAD

**Issue by magnatelee** [rapidsai/legate-boost#148]
Legate has been offering cmake routines that generate boilerplates for library creation and registration, but they are bit-rotted and planned to be deprecated soon. We need to manually add the boilerplate code to legate-boost so it'd be free of any uses of those cmake routines. The code also needs to catch up breaking changes in the TOT legate core, to prepare it for the one-pool transition.

CC @Jacobfaib

**Comment by jameslamb** [comment]
👋 hi @magnatelee 

1. Did you mean to write "we need to manually add the boilerplate code **to `legate-boost`**?"
2. It'd help if the breaking changes from `legate-core` could be published as conda packages... this project has been building against the conda packages since #113
