### ISSUE TITLE
Examples rendering incorrectly in docs

### ISSUE THREAD

**Issue by RAMitchell** [rapidsai/legate-boost#150]
Our examples folder has been included in the docs page, however the images don't render correctly.

This needs some tidying up.

**Comment by jameslamb** [comment]
@RAMitchell I can work on this.

**Comment by jameslamb** [comment]
Example: https://rapidsai.github.io/legate-boost/README.html#probabilistic-regression

![Image](https://github.com/user-attachments/assets/d5951de1-6406-4426-860e-f8a5ff0396ed)

The site has

```html
<img src="/_static/examples/batch_training.png" alt="drawing" width="600"/>
```

but  I think that needs to be a relative link like

```html
<img src="_static/examples/batch_training.png" alt="drawing" width="600"/>
```

I see similar relative links that are working further down in the source (view-source:https://rapidsai.github.io/legate-boost/README.html#probabilistic-regression), e.g.

```html
<script src="[_static/scripts/pydata-sphinx-theme.js?digest=dfe6caa3a7d634c4db9b](https://rapidsai.github.io/legate-boost/_static/scripts/pydata-sphinx-theme.js?digest=dfe6caa3a7d634c4db9b)"></script>
```
